### ISSUE TITLE
Crash when execute app directly

### ISSUE THREAD

**Issue by TangHuaiZhe** [nirix/swift-screencapture#6]
Sorry to disturb.
The project can run and work normally in xcode.
But when I run Product/Example.app directly,It crashed.
`Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: '*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (AVPlayerView) for key (NS.objects); the class may be defined in source code or a library that is not linked'`

PS:Swift version has upgraded to 4

**Comment by TangHuaiZhe** [comment]
Process:               Example [3648]
Path:                  /Users/USER/Library/Developer/Xcode/DerivedData/ScreenCapture-fbeqibqsyebvsvbzbagcgmmybmkt/Build/Products/Debug/Example.app/Contents/MacOS/Example
Identifier:            net.nirix.Example
Version:               1.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Example [3648]
User ID:               501

Date/Time:             2019-10-08 10:19:06.122 +0800
OS Version:            Mac OS X 10.14.5 (18F132)
Report Version:        12
Anonymous UUID:        FDB9C84D-8936-1F4D-8B7B-8F74998BA32B


Time Awake Since Boot: 3100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: '*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (AVPlayerView) for key (NS.objects); the class may be defined in source code or a library that is not linked'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff40284cfd __exceptionPreprocess + 256
1   libobjc.A.dylib                     0x00007fff6a92ea17 objc_exception_throw + 48
2   Foundation                          0x00007fff4257202e -[NSCoder(Exceptions) __failWithExceptionName:errorCode:format:] + 0
3   Foundation                          0x00007fff425721ab -[NSCoder(Exceptions) __failWithExceptionName:errorCode:format:] + 381
4   Foundation                          0x00007fff42434d34 _decodeObjectBinary + 484
5   Foundation                          0x00007fff42436e2e -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 1682
6   Foundation                          0x00007fff424363df -[NSArray(NSArray) initWithCoder:] + 198
7   Foundation                          0x00007fff424354df _decodeObjectBinary + 2447
8   Foundation                          0x00007fff42434a2e _decodeObject + 246
9   Foundation                          0x00007fff4243492a -[NSKeyedUnarchiver decodeObjectForKey:] + 205
10  AppKit                              0x00007fff3d89347e -[NSView initWithCoder:] + 1850
11  Foundation                          0x00007fff424354df _decodeObjectBinary + 2447
12  Foundation                          0x00007fff42434a2e _decodeObject + 246
13  Foundation                          0x00007fff4243492a -[NSKeyedUnarchiver decodeObjectForKey:] + 205
14  AppKit                              0x00007fff3db9a6fa -[NSTabViewItem initWithCoder:] + 164
15  Foundation                          0x00007fff424354df _decodeObjectBinary + 2447
16  Foundation                          0x00007fff42436e2e -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 1682
17  Foundation                          0x00007fff424363df -[NSArray(NSArray) initWithCoder:] + 198
18  Foundation                          0x00007fff424354df _decodeObjectBinary + 2447
19  Foundation                          0x00007fff42434a2e _decodeObject + 246
20  Foundation                          0x00007fff4243492a -[NSKeyedUnarchiver decodeObjectForKey:] + 205
21  AppKit                              0x00007fff3db9a3f6 -[NSTabView initWithCoder:] + 113
22  Foundation                          0x00007fff424354df _decodeObjectBinary + 2447
23  Foundation                          0x00007fff42436e2e -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 1682
24  Foundation                          0x00007fff424363df -[NSArray(NSArray) initWithCoder:] + 198
25  Foundation                          0x00007fff424354df _decodeObjectBinary + 2447
26  Foundation                          0x00007fff42434a2e _decodeObject + 246
27  Foundation                          0x00007fff4243492a -[NSKeyedUnarchiver decodeObjectForKey:] + 205
28  AppKit                              0x00007fff3d89347e -[NSView initWithCoder:] + 1850
29  Foundation                          0x00007fff424354df _decodeObjectBinary + 2447
30  Foundation                          0x00007fff42434a2e _decodeObject + 246
31  Foundation                          0x00007fff4243492a -[NSKeyedUnarchiver decodeObjectForKey:] + 205
32  AppKit                              0x00007fff3d8b9d78 -[NSWindowTemplate initWithCoder:] + 986
33  Foundation                          0x00007fff424354df _decodeObjectBinary + 2447
34  Foundation                          0x00007fff42436e2e -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 1682
35  Foundation                          0x00007fff4244a861 -[NSSet(NSSet) initWithCoder:] + 198
36  Foundation                          0x00007fff424354df _decodeObjectBinary + 2447
37  Foundation                          0x00007fff42434a2e _decodeObject + 246
38  Foundation                          0x00007fff4243492a -[NSKeyedUnarchiver decodeObjectForKey:] + 205
39  AppKit                              0x00007fff3d848eee -[NSIBObjectData initWithCoder:] + 155
40  Foundation                          0x00007fff424354df _decodeObjectBinary + 2447
41  Foundation                          0x00007fff42434a2e _decodeObject + 246
42  Foundation                          0x00007fff4243492a -[NSKeyedUnarchiver decodeObjectForKey:] + 205
43  AppKit                              0x00007fff3d848cc0 loadNib + 317
44  AppKit                              0x00007fff3d8481f4 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 696
45  AppKit                              0x00007fff3d847e39 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 204
46  AppKit                              0x00007fff3d847bfb +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 446
47  AppKit                              0x00007fff3d83bc69 NSApplicationMain + 502
48  Example                             0x0000000103d8d93d main + 13
49  libdyld.dylib                       0x00007fff6c0fc3d5 start + 1
50  ???                                 0x0000000000000001 0x0 + 1

**Comment by rurza** [comment]
It's because AVKit framework isn't linked with your target.

**Comment by TangHuaiZhe** [comment]
@rurza  Thanks.
